from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import Any


def _case_tag(case_name: str) -> str:
    """Convert a case key into a TeX-safe tag (letters/numbers only)."""
    out = []
    for ch in case_name:
        if ch.isalnum():
            out.append(ch)
    tag = "".join(out)
    if not tag:
        raise ValueError(f"Case name {case_name!r} yields empty TeX tag.")
    return tag


def _fmt(x: Any, ndigits: int = 3) -> str:
    """Format numeric scalars for TeX."""
    try:
        return f"{float(x):.{ndigits}f}"
    except Exception as e:
        raise TypeError(f"Expected a numeric scalar, got {x!r}") from e


def write_results_tex(path: Path, results: Mapping[str, Mapping[str, Any]]) -> None:
    """Write solver outputs into a TeX file as \\newcommand macros.

    Args:
        path: Output path for the TeX snippet (e.g., paper/generated/results.tex).
        results: Mapping from case name -> output dict. Each output dict may
            contain keys like "Pi", "U", "t", "t1", "t2", "C".

    Returns:
        None. Writes `path` to disk.
    """
    lines: list[str] = []
    lines.append("% Auto-generated by pytask. Do not edit by hand.")
    lines.append("")

    for case_name, out in results.items():
        tag = _case_tag(case_name)

        def cmd(name: str, value: Any, ndigits: int = 3) -> None:
            lines.append(rf"\newcommand{{\{name}{tag}}}{{{_fmt(value, ndigits)}}}")

        # Always useful scalars if present
        if "Pi" in out:
            cmd("Pi", out["Pi"], 3)
        if "U" in out:
            cmd("U", out["U"], 3)

        # One-period threshold (if you include one-period outputs)
        if "t" in out:
            cmd("t", out["t"], 3)

        # Two-period thresholds
        if "t1" in out:
            cmd("tOne", out["t1"], 3)

        if "t2" in out:
            t2 = out["t2"]
            # Expect length 3 for your 3-outcome setup
            cmd("tTwoA", t2[0], 3)
            cmd("tTwoB", t2[1], 3)
            cmd("tTwoC", t2[2], 3)

        # Continuation profits C_i
        if "C" in out:
            C = out["C"]
            cmd("CA", C[0], 3)
            cmd("CB", C[1], 3)
            cmd("CC", C[2], 3)

        lines.append("")  # blank line between cases

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
